name: "aycomv"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/rails:cached
      - bundle-cache:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/aycomv_development
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1
    restart: unless-stopped
    networks:
      - default
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      # load from env
      POSTGRES_USER: ${AYCOMV_DATABASE_USER}
      POSTGRES_PASSWORD: ${AYCOMV_DATABASE_PASSWORD}

volumes:
  postgres-data:
  bundle-cache:
